openapi: "3.0.0"
info:
  version: 1.0.0
  title: Weather Service
servers:
  - url: http://localhost:8080/
    description: Local deployment of the weather service
tags:
  - name: weather
    description: Weather data for cities
paths:
  /api/weather:
    get:
      tags:
        - weather
      description: Reads weather information for cities
      operationId: getAverages
      parameters:
        - in: query
          name: city
          required: true
          schema:
            type: array
            example: ["Bucuresti, Cluj-Napoca"]
            items:
              type: string
      responses:
        '200':
          description: Weather information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
components:
  schemas:
    Result:
      required:
        - result
      properties:
        result:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/City'
    City:
      required:
        - name
        - temperature
        - wind
      properties:
        name:
          type: string
        temperature:
          type: string
        wind:
          type: string

